### ISSUE TITLE
Implementation-defined and optional features

### ISSUE THREAD

**Issue by jyasskin** [privacycg/privacycg.github.io#10]
The line “Implementation disagreement should not result in implementation-defined behavior or optional features.” shouldn't appear in a charter. It's a good goal for API design, other things equal, but it's not appropriate for a charter to presuppose answers to API design questions. It's especially inappropriate at the incubation phase where
1. having different implementations test different variations of the same API is likely to help us gather the feedback needed to define the best API, and
1. the API will be released from this constraint when it moves to a working group that isn't covered by this charter restriction.

Some examples of APIs where this restriction would have been a bad idea:

* Geolocation, where the design of the permission dialog is implementation-defined, and where that design has improved over time as implementations were allowed to experiment on it.
* `one-time-code` where actually filling the code in from SMS is [optional](https://github.com/whatwg/html/issues/3745#issuecomment-487101498).

**Comment by erik-anderson** [comment]
The spirit of this, as you noted, was to encourage specifying things with enough detail to ensure interoperability. Your concerns are reasonable, though, so I agree that we should remove this text.

**Comment by hober** [comment]
Sounds good to me. I've dropped this sentence in 0a73ce3, part of PR #5.

**Comment by TanviHacks** [comment]
Removing this sentence is also fine by me.

**Comment by hober** [comment]
Removed in 32bd9e8.
