### ISSUE TITLE
Charter should more clearly distinguish between Proposals and Work Items

### ISSUE THREAD

**Issue by hober** [privacycg/privacycg.github.io#11]
It's clear that this can still be confusing. Some notes on this from #5:

@jyasskin [wrote](https://github.com/privacycg/privacycg.github.io/pull/5#discussion_r376660692):

> Is there a concrete difference between how the CG will interact with a Proposal vs a Work Item? It looks like a sufficiently complex proposal can get a repository before multiple engines have expressed interest, and the CG discusses them similarly.
> 
> Would it shorten or simplify the charter to say that everything's a Proposal, and the chairs will keep a list of proposals for which 2 engines have expressed interest?

@travisleithead [replied](https://github.com/privacycg/privacycg.github.io/pull/5#discussion_r376672766):

> The major difference seems to be around the allocation of [potentially scarce] Editors, which are appointed by the chairs (do these editors have to be members of the CG?) to advance the work item. The Editors then takeover much of the responsibility of "directing the work" until they judge its ready to advance beyond the CG. Did I get that right?
> 
> What does this mean for proposals that have a highly-engaged and willing "owner"/"creator"? If the chairs do not want to see the proposal advance (or the proposal doesn't meet the implementer criteria), I'm not sure they could do much to stop a pro-active proposal owner (not an officially minted editor) from carrying on. It seems the purpose of promotion to Work Item then is to lend a helping hand to good proposals with less-active owners and get them moving even faster in the process. Might be worth calling out the rationale a bit more.

I [replied](https://github.com/privacycg/privacycg.github.io/pull/5#discussion_r376673576):

> Hmm. The intent is that the output of the proposal phase is an explainer, and the output of the work item phase is a revised explainer and a draft spec. This is spelled out in the proposals repo https://github.com/privacycg/proposals but not in the charter. I'll try to figure out how to incorporate that here. Thanks!

**Comment by cwilso** [comment]
I think this is sufficient, but @jyasskin should weigh in.

**Comment by jyasskin** [comment]
Sorry for commenting slowly. Before doing a detailed review of #14, I want to dig a bit more into what we actually want here.

@hober, it looks like your intent is that the CG can collaborate on an explainer with less than 2 implementers' support, but that it won't collaborate on a specification unless 2 implementers agree.

In the event that some Proposal is clearly going to be implemented in the engine, and only Blink is interested in implementing, but a couple browsers based on Blink are planning to ship, I'd like a specification to exist before those browsers ship. Where do we want that specification to live? Should the Blink developers request that the proposal be migrated out of the CG at the point they're ready to start a specification? Should the specification live in an independent repository? Are we worried about losing privacy expert feedback on Blink-only features? Should we wait to worry about this (and plan to amend the charter) when and if it happens?

In https://github.com/privacycg/privacycg.github.io/issues/9#issuecomment-585363690, @erik-anderson worries that we might not be able to even tell which browsers count as implementers before a specification is written, which would be mitigated if the CG could collaborate on a specification at the Proposal stage.

I do think it's reasonable for the charter to say that the CG won't publish a Final Community Report/Final Specification or support migration to a WG without multi-implementer support, but that seems to be a later bar than @hober wants.

**Comment by cwilso** [comment]
I'd point out there's a clear ability to NOT support migration to a WG without multi-implementer support already.  I think the concern is focusing the CG's work time and attention on broadly-desired features, which I agree with.  I do NOT agree with the definition of implementer devaluing shared implementations, which is why I filed #9.

**Comment by hober** [comment]
@jyasskin [wrote](https://github.com/privacycg/privacycg.github.io/issues/11#issuecomment-585479090), in a somewhat different order:

> Should we wait to worry about this (and plan to amend the charter) when and if it happens?

Probably, yes. It's often easier to figure out what we'd like to change about a process when there's a concrete failure to look at.

> It looks like your intent is that the CG can collaborate on an explainer with less than 2 implementers' support, but that it won't collaborate on a specification unless 2 implementers agree.

Yes, that's a reasonable summary of my thinking here.

I think one of the biggest lessons learned from the earlier incubation flows we've tried in other CGs is that incubation artifacts that look like specs often get taken to be them by the wider community.

I believe that we (people working on web standards in general, or the W3C in particular perhaps) should refrain from producing things that look like specs that will not be independently, interoperably implemented.

> In the event that some Proposal is clearly going to be implemented in the engine, and only Blink is interested in implementing, but a couple browsers based on Blink are planning to ship, I'd like a specification to exist before those browsers ship.

Ideally, you'd keep engaging with the other engines to try to come up with something that they might also be willing to implement. I think we all prefer browsers to implement consensus specifications that have broad support and advance the industry.

In the event that you get pushback, I hope you'll weigh that pushback carefully and try to address it. If nonetheless, you want to go ahead after not getting support from the other engines, you're working on a Blink-only feature. And while I hope you would document such work somewhere, it's out of scope for this CG (and, arguably, W3C).

> Where do we want that specification to live?

Somewhere on https://www.chromium.org/ perhaps, or in an incubation venue that's comfortable with hosting specs for Blink-only features.

> Should the Blink developers request that the proposal be migrated out of the CG at the point they're ready to start a specification? Should the specification live in an independent repository?

An FYI is nice, of course, but clearly no permission is required to start a spec elsewhere, and whether you want to withdraw the proposal from the CG at that point is up to you.

> Are we worried about losing privacy expert feedback on Blink-only features?

I think the folks working on Blink-only features should seek review from experts in a number of areas, including privacy. I think encouraging them to do so is out of scope for this charter, though.

**Comment by jyasskin** [comment]
@hober, thanks for the clarity. I'll go over #14 with that interpretation over the next couple days, and I'll try to avoid presupposing any particular resolution to #9.

You wrote, "incubation artifacts that look like specs often get taken to be them by the wider community". Do you mean that a document like https://webbluetoothcg.github.io/web-bluetooth/ (sigh, https://github.com/tabatkins/bikeshed/pull/1604) is not a "specification" because it doesn't have multi-engine agreement? I would say that it's not a "standard" and that we can't tell whether it's a _good_ specification without multiple independent implementations, but that it's still a "specification". We can work through any disagreement there in another forum, but I wanted to make sure there actually is disagreement.

**Comment by hober** [comment]
> @hober, thanks for the clarity. I'll go over #14 with that interpretation over the next couple days, and I'll try to avoid presupposing any particular resolution to #9.

Thanks for your reviews on #14. I think the PR is much improved as a result.

> You wrote, "incubation artifacts that look like specs often get taken to be them by the wider community". Do you mean that a document like https://webbluetoothcg.github.io/web-bluetooth/ (sigh, [tabatkins/bikeshed#1604](https://github.com/tabatkins/bikeshed/pull/1604)) is not a "specification" because it doesn't have multi-engine agreement? I would say that it's not a "standard" and that we can't tell whether it's a _good_ specification without multiple independent implementations, but that it's still a "specification".

Fair point.
