### ISSUE TITLE
License

### ISSUE THREAD

**Issue by martinthomson** [privacycg/privacycg.github.io#33]
I would like to "borrow" some of the content of this repository.  What license governs this work?

**Comment by hober** [comment]
Charter text is under two licenses, as documented [in its footer](https://privacycg.github.io/charter.html#about): the W3C Software and Document License & the Creative Commons Attribution 4.0 International License.

As for the rest of the contents, I suppose that's rather ambiguous. I don't recall explicitly deciding on a license for this repository in the past. When we did talk about licensing while setting the group up, the topic was focused on the group's deliverables, and not on administrivia like this.

**Comment by martinthomson** [comment]
Thanks.   I didn't read that as a statement of license for this document, just an indication of where it came from.  My mistake.
