### ISSUE TITLE
Why the limit of three chairs?

### ISSUE THREAD

**Issue by cwilso** [privacycg/privacycg.github.io#8]
"There can be at most three Chairs."  seems like a curious limitation for no particular purpose, and should be struck.  If the group wants more chairs, they should add them; if they don't, they shouldn't.  For example, WICG currently has four chairs, and could probably work quite well with more.

**Comment by TanviHacks** [comment]
I am okay with removing the max chair constraints in the charter.  But I do think that more than three chairs does add extra overhead.

**Comment by cwilso** [comment]
(Note I was not actually asking to add a chair; just asking why the limitation.)

**Comment by erik-anderson** [comment]
I'm supportive of removing the text that specifies a limit of three chairs.

**Comment by hober** [comment]
In my experience, 1 or 2 chairs is usually sufficient for a CG or WG, and the value of adding additional chairs diminishes very sharply. While I don't think having a hard-coded limit is strictly necessary, I do think it's reasonable to try one in a CG—CGs, after all, are [laboratories](https://en.wikipedia.org/wiki/Laboratories_of_democracy) where process innovations may be tried at low risk to the rest of the consortium. (See also [this comment of mine](https://github.com/privacycg/privacycg.github.io/issues/6#issuecomment-583075274) on issue #6.)

That said, if this is really something that would cause an organization to choose not to join the CG, that would be new information that could easily lead to striking the text from the charter.

**Comment by travisleithead** [comment]
I also find the 3 chair limit odd; I supposed it had to do with the clause about:

> If consensus cannot be found among the Chairs, and unanimity is not otherwise required, the Chairs may make decisions by supermajority (at least 2/3rds support)

I'd love to drop both parts.

Personally, I think if you can't get the chairs to be reasonable, then trying to enforce this 2/3rds support thing will just make it worse. I'd rather invite the chairs to continue to work toward unanimity possibly by adjusting or dropping the contentious issue. I understand we are preparing for contention here, but I'd rather have the stated rule be unanimous consent (another good reason to keep the number of chairs small).

(If chairs drop to 2, then what does 2/3rds mean then?)

**Comment by travisleithead** [comment]
Maybe a new issue, but an Election process for chairs in the charter? ...why? I mean I don't like STV either...but maybe we should propose this nice and lightweight process to the W3C Process doc instead? :)

**Comment by jyasskin** [comment]
@travisleithead The chair selection bit is copied from the [sample charter](https://w3c.github.io/cg-charter/CGCharter.html#chairs), so it's at least not novel.

**Comment by hober** [comment]
> Maybe a new issue, but an Election process for chairs in the charter? ...why? I mean I don't like STV either...but maybe we should propose this nice and lightweight process to the W3C Process doc instead? :)

It's the same chair election process WICG uses IIRC. Like @jyasskin said, it's from the sample CG charter.

**Comment by travisleithead** [comment]
Got it. Thanks.

**Comment by cwilso** [comment]
Given that this charter was privately developed, I don't think it's reasonable to "try out" limiting the number of chairs in this group.

**Comment by hober** [comment]
> (If chairs drop to 2, then what does 2/3rds mean then?)

2/3rds means unanimity when n = 2.

Given @TanviHacks & @erik-anderson's comments, I've got a change which drops this limit as part of #5, in 4870f74. Note to self: close this issue when the PR lands.

**Comment by hober** [comment]
Sentence removed in 32bd9e8.
